pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t docker-atlassian-jira-all:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/docker-atlassian-jira-all
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
      - v4.5.0
    when:
      branch: master
      event: [ push, deployment ]
